[package]
name = "graliffer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.89"
unicode-segmentation = "1.12.0"
strum = "0.26.3"
strum_macros = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eframe = "0.31.0"
egui = "0.31.0"
